import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@flavioespinoza/salsa-ui/dist/index.css'
import './globals.css'

const inter = Inter({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'], // Light (300), Regular (400), Medium (500), Bold (700)
	variable: '--font-inter'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={inter.className} suppressHydrationWarning>
			<body>{children}</body>
		</html>
	)
}
